Add commits from previous repo
starburstlabs/NotificationBanner pull request #1
Opened 2022-06-27 19:51 UTC by scruff311

This PR re-applies the commits from https://github.com/scruff311/NotificationBanner which primarily allow us to use translucent backgrounds for banners and locks the width of the banners on iPad.

2022-06-27 20:08 UTC, zhanfengh requested changes
Looks great!
Should we add this commit as well? https://github.com/scruff311/NotificationBanner/commit/a31d2c55cc99d9e76b00d8e1eeea9d4e31719d66

2022-06-27 21:25 UTC, scruff311 commented
> Looks great! Should we add this commit as well? [scruff311@a31d2c5](https://github.com/scruff311/NotificationBanner/commit/a31d2c55cc99d9e76b00d8e1eeea9d4e31719d66)

Good eye, but I skipped that one because it was changed upstream and was not necessary anymore.

2022-06-27 21:30 UTC, zhanfengh approved these changes
Ah, I see
https://github.com/starburstlabs/NotificationBanner/blob/master/NotificationBanner/Classes/BaseNotificationBanner.swift#L24

Thanks! Approved

2022-06-28 14:24 UTC, treiff approved these changes

2022-06-28 14:24 UTC, merged